### ISSUE TITLE
Set up script that extracts the data from API and populated a local duckdb instance 

### ISSUE THREAD

**Issue by lfunderburk** [beltran-oscar/ETL-pipeline-ML#3]
Here are a couple blogs to help you upgrade the scripts:

https://ploomber-sql.readthedocs.io/en/latest/packaging-your-sql-project/intro-to-python-scripting-and-pipelines.html

Here is a script with sample functions to load your data from an API into a duckdb instance
https://ploomber-sql.readthedocs.io/en/latest/packaging-your-sql-project/intro-to-etl-pipelines-with-python-and-sql.html

https://ploomber-sql.readthedocs.io/en/latest/mini-projects/recommendation-system/setting-up-etl.html#creating-a-python-script-to-extract-data

A full script with a complete extract, clean and load workflow

https://github.com/ploomber/sql/blob/main/mini-projects/movie-rec-system/movie_rec_system/etl/extract.py

**Comment by lfunderburk** [comment]
Goal is to take

```
# Define the API URL
api_url = "https://api.openaq.org/v2/measurements"

# Define the query parameters
params = {
    "location_id": "380422",
    "parameter": ["pressure", "temperature", "um003", "um025", "um010", "pm10", "um100", "pm1", "um005", "humidity", "um050", "pm25"],
    "limit": 100000,
    "api_key": "bca2413f10b586fc8e29e6a7712258baf2d528cfdfc06dcba5bf1cc44e714a9c"
}

# Make the GET request
response = requests.get(api_url, params=params)


# Check if the request was successful (status code 200)
if response.status_code == 200:
    data = response.json()
    output = data['results']
    df = pd.DataFrame(output)
    # Extract local time from date column (dictionary)
    df['local_time'] = df['date'].apply(lambda x: x['local'])
    df['local_time'] = pd.to_datetime(df['local_time'])
```

and transform it into stand alone script undet /src/extract.py

it should shave the response into a duckdb instance

**Comment by lfunderburk** [comment]
Example

```
def save_to_duckdb(df, table_name, db_path):
    """Save dataframe to duckdb"""
    conn = duckdb.connect(db_path)
    conn.register('df', df)
    
    # Check if table already exists, if not, create it
    tables = conn.execute("SHOW TABLES").fetchall()
    if table_name not in [table[0] for table in tables]:
        conn.execute(f"CREATE TABLE {table_name} AS SELECT * FROM df")
    
    conn.close()
```

And

```
df = # your data frame from the api
clean_df = # apply cleaning function
table_name = 'your_table'
# Save the cleaned data to DuckDB
save_to_duckdb(df, table_name, f'{data_dir}/data.duckdb')
```

**Comment by lfunderburk** [comment]
@beltran-oscar  this needs to be completed before refactoring the notebook for #4 
let me know if you have questions

**Comment by aleivaar94** [comment]
I made the script in the data-eng branch
